### ISSUE TITLE
How can i install this?

### ISSUE THREAD

**Issue by MrFallen** [HugoJF/csgo-pipeline#1]
I want install pipeline + csgo sessions - https://github.com/HugoJF/csgo-sessions :(
I need guide.

**Comment by HugoJF** [comment]
If I'm honest, I really don't remember how everything works.

I actually forgot this project didn't have a README, and I might give writing it a shot this week.

**Comment by MrFallen** [comment]
@HugoJF I would be very pleased if you could help me figure out how it works. I especially don’t understand how daemon works. :(

**Comment by MrFallen** [comment]
If I want using Pipeline I must install CSGOServerAPI?

**Comment by HugoJF** [comment]
I think so, I haven't used this project in a while. The API is used to make sure the servers are pointing to the event ingest daemon.
