### ISSUE TITLE
How can i fix it?

### ISSUE THREAD

**Issue by MrFallen** [HugoJF/csgo-pipeline#2]
![image](https://user-images.githubusercontent.com/5339386/84292698-0b33c480-ab8a-11ea-8fc1-f94809ccf805.png)
Error.
My English is sucks. I warn u.

**Comment by HugoJF** [comment]
It seems like I'm using Babel for this project, run `npm run babel` and execute what is transpiled to `./build`

**Comment by MrFallen** [comment]
Error. Hmmm...
![image](https://user-images.githubusercontent.com/5339386/84330701-781b7e80-abcb-11ea-8e31-12cb206a0727.png)

**Comment by MrFallen** [comment]
Okay. I fixed it. But i have this message:
![image](https://user-images.githubusercontent.com/5339386/84333161-45c14f80-abd2-11ea-88ba-c7058d30adbe.png)

:(

**Comment by MrFallen** [comment]
APP URL WITH PIPELINE - 192.168.0.108

daemon .env:
API_URL=http://192.168.0.108/api
TOKEN=sessions
BASE_PORT=80
LISTENING_IP=192.168.0.108

Whats wrong?

**Comment by HugoJF** [comment]
What Node version are you running? I'm using 5.6 on Ubuntu 20.04 and managed to transpile everything correctly.

Cloned my repository, ran `npm install` and `npm run babel` just fine.

As for `Empty body from API request` you need to set `API_URL` to an instance of [https://github.com/HugoJF/csgo-server-api](https://github.com/HugoJF/csgo-server-api).

EDIT: Just added a Dockerfile for `csgo-server-api`, that should make things easier to run.

**Comment by HugoJF** [comment]
Finished `csgo-server-api` README, should be pretty easy to get it up and running. If you have any problems, please create an issue there.

I'll be closing this issue as you seem to have fixed your installation.
